controller_list:
  - name: fake_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_roll_joint
      - elbow_pan_joint
      - elbow_pitch_joint
      - gripper_pan_joint
      - gripper_pitch_joint
  - name: fake_gripper_controller
    joints:
      - left_gripper_joint
      - right_gripper_joint